name: Apptainer Build
on: workflow_dispatch

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build Apptainer image
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install Apptainer
        uses: uw-psych/apptainer-actions/setup@dev
      - name: Check out code for the container build
        uses: actions/checkout@v4
      - name: Build Container for Workshop 1 (single-job.py)
        uses: uw-psych/apptainer-actions/build-and-push@dev
        with:
          deffile: workshop-01/Singularity
          build-args: PY_FILE=single-job.py
          image-name: w01-single-job
      - name: Build Container for Workshop 1 (array-job.py)
        uses: uw-psych/apptainer-actions/build-and-push@dev
        with:
          deffile: workshop-01/Singularity
          build-args: PY_FILE=array-job.py
          image-name: w01-array-job
